// front/angular/src/app/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductsComponent } from "../products/products.component";
import { ProductComponent } from "../products/product/product.component";
import { RouterLink, RouterOutlet } from '@angular/router';
import productsService from '../products/products-service';
import { cProduct, product } from '../products/products-model';
import { cartService } from '../cart/cart-service';

@Component({
  selector: 'app-nav-bar',
  standalone: true,
  imports: [ProductsComponent, ProductComponent, RouterOutlet, RouterLink],
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.css',
})
export class NavBarComponent implements OnInit {
products : cProduct[] = [];
count !: number;

constructor(private _cartService:cartService) {
}


calc = ()=>{
  this.count = 0;
  this.products.forEach((product)=>{
    this.count += product.count;
  })
}

sub = ()=>{
  this._cartService.productAddedToCart.subscribe((product)=>{
    this.products = product;
    this.calc();
  })
}
  ngOnInit(): void {
    this.products=this._cartService.getCartProducts();
    this.calc();
    this.sub();
  }
}

<div class="container">
  <div class="navbar">
    <h1 class="title"><a routerLink="/">E-Commerce</a></h1>
    <button class="navbar-toggler" type="button">
      &dArr;
    </button>
    <ul class=" nav-items">
      <li>
        <a class="nav-item" routerLink="/"> Home </a>
      </li>
      <li>
        <a class="nav-item" routerLink="/products"> Products </a>
      </li>
      <li>
        <a class="nav-item" id="cart" routerLink="/cart">{{'Cart ('+ count +')'}}</a>
      </li>
    </ul>
  </div>
      <div class="main">
        <router-outlet></router-outlet>
    </div>
</div>

// front/react/src/Components/Navbar.js

import { Link } from 'react-router-dom'
import style from './Navbar.module.css'
import { useSelector } from 'react-redux'
import { useEffect, useState } from 'react'


const Navbar = ()=>{
    const products = useSelector((state)=>state.cart)
    const [count,setCount]=useState(0)

    const calc =()=>{
        var counter =0;
        products.forEach((el)=>{
            counter += el.count
        })
        setCount(counter)
    }
    useEffect(()=>{
        calc();
    },[products])
return(
    <>
        <div className={style['container']}>
            <div className={style['navbar']}>
                <h1 className={style['title']}><Link to="/">E-Commerce</Link></h1>
                <button className={style['navbar-toggler']} type="button">
                &dArr;
                </button>
                <ul className={style['nav-items']}>
                    <li>
                        <Link className={style["nav-item"]} to="/"> Home </Link>
                    </li>
                    <li>
                        <Link className={style["nav-item"]} to="/products"> Products </Link>
                    </li>
                    <li>
                        <Link className={style["nav-item"]} id="cart" to="/cart">Cart ({count})</Link>
                    </li>
                </ul>
            </div>
        </div>
    </>
)
}

export default Navbar
