// front/react/src/Components/Products/Product.js
import { useDispatch } from 'react-redux';
import style from './Product.module.css'
import { addProduct } from '../../rtk/cartSlice';

const Product =({product})=>{

    const dispatch = useDispatch()

    return(
        <div className={style["card"]}>
            <img src={product.image} alt={product.title}/>
            <div className={style["card-body"]}>
                <h3>{product.title}</h3>
                <h4>Price : {product.price} $</h4>
                <button className={style["btn"]} onClick={()=>dispatch(addProduct(product))} >Add to Cart</button>
            </div>
        </div>
    )
}

export default Product;

// front/angular/src/app/products/product/product.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { product } from '../products-model';
import productsService from '../products-service';

@Component({
  selector: 'app-product',
  standalone: true,
  imports: [],
  templateUrl: './product.component.html',
  styleUrl: './product.component.css'
})
export class ProductComponent implements OnInit {
  @Input() product !:product

  constructor(private _productService:productsService) {

  }
  ngOnInit(): void {

  }

  onSelect(){
    this._productService.addProductToCart(this.product);
  }

}

<div class="card">
  <img src={{product.image}} >
  <div class="card-body">
    <h3>{{product.title}}</h3>
    <h4>Price : {{product.price}} $</h4>
    <button class="btn" (click)="onSelect()">Add to Cart</button>
  </div>
</div>
