// front/angular/src/app/cart/cart-list/cart-list.component.ts
import { Component, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import productsService from '../../products/products-service';
import { cProduct, fProduct, product } from '../../products/products-model';
import { CommonModule } from '@angular/common';
import { cartService } from '../cart-service';

@Component({
  selector: 'app-cart-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './cart-list.component.html',
  styleUrl: './cart-list.component.css'
})

export class CartListComponent implements OnInit{
  products :fProduct[]=[];
  t:number =0;
  c:number = 0;

  constructor(private _cartServic:cartService) {}



  sum(count:number,price:number)
  {
    return +(count*price).toFixed(2)
  }

  modify(prod:cProduct){
    const el = {} as fProduct
    el.product = prod;
    el.total = this.sum(prod.count,prod.price);
    this.c += prod.count;
    this.t += el.total;
    this.products.push(el)
  }

  sub=()=>{
    this._cartServic.productAddedToCart.subscribe((products)=>{
      this.t=0;
      this.c=0;
      products.forEach((product)=>{
        this.modify(product);
      })
    })
  }

  ngOnInit(): void {
    this._cartServic.getCartProducts().forEach((prod)=>{
      this.modify(prod)
    });
    this.sub();
  }

  inc(prod:cProduct){
    this.products=[];
    this._cartServic.addProductToCart(new product(prod.id,prod.title,prod.image,prod.price))
}
dec(i:number){
  this.products=[];
  this._cartServic.removeProductFromCart(i);
}
remove(i:number){
  this.products=[];
  this._cartServic.removeProductFromCart(i,0);
}
}

<div class="card">
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Price</th>
      <th>Count</th>
      <th>Total</th>
      <th>Control</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let product of products,index as i">
      <td>
        {{i+1}}
      </td>
      <td>
        {{product.product.title}}
      </td>
      <td>
        {{product.product.price}} $
      </td>
      <td>
        <button class="btn" (click)="inc(product.product)">+</button>
        <span class="count">{{product.product.count}}</span>
        <button class="btn" (click)="dec(i)">-</button>
      </td>
      <td>
        {{product.total}} $
      </td>
      <td>
        <button class="btn-red" (click)="remove(i)">Remove</button>
      </td>
    </tr>
    <tr style="color: white; background-color: gray; position: sticky;">
      <td><B>Sum</B></td>
      <td>-</td>
      <td>-</td>
      <td><B>{{c}}</B></td>
      <td><B>{{t.toFixed(2)}} $</B></td>
      <td>-</td>
    </tr>
  </tbody>
</table>
</div>

// front/react/src/Components/Cart/CartList.js
import { useEffect, useState } from "react";
import styles from './CartList.module.css'
import { useDispatch, useSelector } from "react-redux";
import { addProduct, removeProduct } from "../../rtk/cartSlice";

const CartList =()=>{

    const products = useSelector((state)=>state.cart);
    const [sum,setSum]=useState({count:0,total:0});
    const dispatch = useDispatch();
    var dec = 1;
    useEffect(()=>{
        var c=0;
        var t=0;
        products.forEach(element => {
            c += element.count;
            t += element.count*element.price;
        });
        setSum({count:c,total:t.toFixed(2)})
    },[products])

    return(
    <>
    <div className={styles["card"]} >
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Count</th>
                    <th>Total</th>
                    <th>Control</th>
                </tr>
            </thead>
            <tbody>
                {products.length > 0 && products.map((product,i)=>
                    <tr key={product.id}>
                        <td>
                            {i+1}
                        </td>
                        <td>
                            {product.title}
                        </td>
                        <td>
                            {product.price} $
                        </td>
                        <td>
                            <button className={styles["btn"]} onClick={()=>dispatch(addProduct(product))}>+</button>
                            <span className={styles["count"]}>{product.count}</span>
                            <button className={styles["btn"]} onClick={()=>{dec=1; dispatch(removeProduct({i,dec}))}}>-</button>
                        </td>
                        <td>
                            {product.count*product.price} $
                        </td>
                        <td>
                            <button className={styles["btn-red"]} onClick={()=>{dec=0;dispatch(removeProduct({i,dec}))}}>Remove</button>
                        </td>
                    </tr>
                )}
                <tr style={{color: 'white', backgroundColor: 'gray', position: 'sticky'}}>
                    <td><b>Sum</b></td>
                    <td>-</td>
                    <td>-</td>
                    <td><b>{sum.count}</b></td>
                    <td><b>{sum.total} $</b></td>
                    <td>-</td>
                </tr>
            </tbody>
        </table>
    </div>
    </>
)
}

export default CartList;
