// front/react/src/Components/Products/Products.js
import { useEffect, useState } from "react"
import style from './Products.module.css'
import Product from "./Product"

const Products = ()=>{

    const [categories,setCategories] = useState([])
    const [products,setProducts] = useState([])

    const clear = ()=>{
        document.getElementById("all")?.classList.remove(style['active']);
        [...categories].forEach((cat)=>{
            document.getElementById(cat.title)?.classList.remove(style['active']);
        })
    }

    const getCategories = async ()=>{
        const api = await fetch('https://localhost:7005/category');
        const res = await api.json();
        setCategories(res.data);
    }

    const getProducts = async ()=>{
        const api = await fetch('https://localhost:7005/product/all');
        const res = await api.json();
        setProducts(res.data);
        clear();
        document.getElementById('all')?.classList.add(style['active'])
    }

    const getProductsByCat = async (cat)=>{
        const api = await fetch('https://localhost:7005/product/category/'+cat.id.toString());
        const res = await api.json();
        setProducts(res.data);
        clear();
        document.getElementById(cat.title)?.classList.add(style['active']);
    }

    useEffect(()=>{
        getCategories();
        getProducts();
    },[])

    return(
        <>
            <div className={style['container']}>
                <button id="all" onClick={getProducts}>All</button>
                {categories.length && categories.map((cat)=><button key={cat.id} id={cat.title} onClick={()=>getProductsByCat(cat)}>{cat.title}</button>)}
            </div>
            <div className={style["row"]}>
                {products && products.map((product)=>
                    <Product product={product} key={product.id} />
                )}
            </div>
        </>
    )
}

export default Products;

// front/angular/src/app/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ProductComponent } from "./product/product.component";
import productsService from './products-service';
import { category, product } from './products-model';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [RouterOutlet, ProductComponent, CommonModule],
  templateUrl: './products.component.html',
  styleUrl: './products.component.css'
})
export class ProductsComponent implements OnInit {

  products !: product[]
  categories :category[] = []
  constructor(private _productsService :productsService) {
  }

  clear(){
    [...this.categories,{id:0,title:'all'}].forEach(el=>{
      document.getElementById(el.title)?.classList.remove('active');
    })
  }

  getAll(){
    this._productsService.getProducts().subscribe(data =>{
      this.products = data;
    });
    this.clear();
    document.getElementById('all')?.classList.add('active')
  }

  ngOnInit(): void {
    this.getAll();
    this._productsService.getCategories().subscribe(data => this.categories=data.data)
  }

  handleClick(cat:category){
    this._productsService.getProductsByCategories(cat.id).subscribe(data =>{
      this.products = data;
    });
    this.clear();
    document.getElementById(cat.title)?.classList.add('active');
  }
}

<div class="container">
  <button (click)="getAll()" id="all"> All </button>
  <button *ngFor="let cat of categories" (click)="handleClick(cat)" id={{cat.title}}>{{cat.title}}</button>
</div>
  <div class="row">
    <app-product *ngFor="let product of products"
    [product]="product"></app-product>
  </div>
